### ISSUE TITLE
Request release

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [project-fifo/rebar3_lint#18]
I'd like to request a release of `rebar3_lint`, if possible, after https://github.com/project-fifo/rebar3_lint/pull/17 is merged. Thanks.

**Comment by Licenser** [comment]
published as `0.2.0` (bumped a minor since elvis bumped a minor)

**Comment by paulo-ferraz-oliveira** [comment]
You were too fast!

I was going to propose we move from `{deps, [{elvis, "~>0.6.1", {pkg, elvis_core}}]}` to `{deps, [{elvis_core, "~>0.6.1"}]}`, but we can do it later.

Any reason to have it like that in `rebar.config`?

Related to https://github.com/inaka/elvis/issues/491.

**Comment by Licenser** [comment]
:joy: I try to merge any contribution that's stright foward and not in Draft ASAP :) if someone puts in the effort their work should't be hold up by me not clicking merge ;)

But if you want to throw in another PR on that 👍 it'll be `0.2.1` then :D

**Comment by paulo-ferraz-oliveira** [comment]
Nice.

Don't worry, though. We'll soon (hopefully) be releasing a new elvis version and with that I'll probably PR again.
