### ISSUE TITLE
Version 0.3.0 is not backward compatible

### ISSUE THREAD

**Issue by tothlac** [project-fifo/rebar3_lint#21]
It looks like older version which worked perfectly on older versions reports these errors:

```
# src/myapp.erl [FAIL]
Error: 'undef' while applying rule 'no_tabs'.
Error: 'undef' while applying rule 'line_length'.
```
You don't have these rules implemented anymore or do you have an idea what can be the problem?

**Comment by elbrujohalcon** [comment]
These rules are in a different module now. elvis_text_style, IIRC. There's a migration guide in elvis_core repo somewhere.

**Comment by elbrujohalcon** [comment]
https://github.com/inaka/elvis_core/blob/master/MIGRATION.md

**Comment by tothlac** [comment]
Thanks. We can do that, but actually we will have to do this on 100 repositories so it will still take some time.

**Comment by tothlac** [comment]
I've tried it, and it works perfectly. Do you have an idea how to fix the other issue : https://github.com/project-fifo/rebar3_lint/issues/22 ?

**Comment by elbrujohalcon** [comment]
I replied there.
