### ISSUE TITLE
New type of errors not compatible with previous versions?

### ISSUE THREAD

**Issue by tothlac** [project-fifo/rebar3_lint#22]
Using version 0.2.0 I did not have any kind of problems reported by elvis. Now after hexpm package 0.3.0 was copied to hexpm I have errors like this:
```
  - atom_naming_convention
    - Atom "allowEmptyValue" on line 1177 does not respect the format defined by the regular expression '"^([a-z][a-z0-9]*_?)*(_SUITE)?$"'.
    - Atom "requestBody" on line 1208 does not respect the format defined by the regular expression '"^([a-z][a-z0-9]*_?)*(_SUITE)?$"'.
 ```

I do agree that field name in maps && records should be named differently. Unfortunately the problem is that we have 100 repositories here containing thousands of erlang modules. Fixing all of these problems by changing the field names would require a huge amount of work.

Would it be possible to make elvis backward compatible, meaning by default this validation is turned off and only if someone would like to use it they should enable the rule in elvis.config?

    -

**Comment by tothlac** [comment]
That would be actually also a solution for us if the rule could be completely disabled? Is there such an option?

**Comment by elbrujohalcon** [comment]
Yeah. You have multiple options.
Check elvis_core's Readme.
You list ignored files in elvis.config... Or rebar.config... Or you can use -elvis directly in your modules.

**Comment by elbrujohalcon** [comment]
And for that rule in particular... You can specify the regex used to check the atoms.

**Comment by tothlac** [comment]
It looks like `                      {elvis_style, atom_naming_convention, disable} ` works perfectly.
Would you also recommend using this option - as a quickfix for this problem - if we only want backward compatibility with version 0.2.0  ?
Later on of course this rule can be quite useful since I also don't like those field names mentioned above...

**Comment by tothlac** [comment]
So right now I will probably disable it using `{elvis_style, atom_naming_convention, disable}`, and later on all atom names should be fixed so I will add this rule again back to elvis.config.

**Comment by elbrujohalcon** [comment]
Yeah. That's fine.

**Comment by tothlac** [comment]
Ok. Thank you for your help. It was fixed quickly :)
Merry Christmas and Happy New Year!

**Comment by tothlac** [comment]
Both tickets can be closed now...
