### ISSUE TITLE
elvis_output_format does not work

### ISSUE THREAD

**Issue by sirikid** [project-fifo/rebar3_lint#33]
how do I set this cursed option?

**Comment by paulo-ferraz-oliveira** [comment]
Hi. How are you setting it?

**Comment by paulo-ferraz-oliveira** [comment]
@elbrujohalcon: I also think there's a bug in the code. `:set_env`, for this option, is happening on top of `elvis`, not `elvis_core`.

**Comment by paulo-ferraz-oliveira** [comment]
I tested this myself and ended up with https://github.com/project-fifo/rebar3_lint/pull/34. Keep an eye out for a future merge+release.

**Comment by paulo-ferraz-oliveira** [comment]
This is published in [Hex (0.4.1)](https://hex.pm/packages/rebar3_lint/0.4.1), and tagged in [GitHub (v0.4.1)](https://github.com/project-fifo/rebar3_lint/releases/tag/v0.4.1).

**Comment by sirikid** [comment]
thanks a lot, it works
