### ISSUE TITLE
"rebar3 lint" doesn't work

### ISSUE THREAD

**Issue by marianoguerra** [project-fifo/rebar3_lint#6]
from the readme, running "rebar3 lint" doesn't work, but:

    rebar3 as lint lint

works

**Comment by cypherfox** [comment]
"rebar3 lint" works fine for me. "rebar3 as lint lint", does not.

**Comment by Licenser** [comment]
good catch, it depends on the profile `rebar3 lint` should work if `rebar3_lint` is a top level plugin but the docs don't describe it that way (and I think it is better to put them in a profile too).

**Comment by Licenser** [comment]
also sorry about the late reply and fix, didn't saw this until todayl
