### ISSUE TITLE
Change in release tags format

### ISSUE THREAD

**Issue by aronisstav** [project-fifo/rebar3_lint#9]
Hello and many thanks for this very useful drop-in enabler for Elvis!

Is there any reason why the format of the release tags changed 'recently' to have a 'v' in front of the name? This change e.g. breaks compatibility with semantic versioning.

**Comment by aronisstav** [comment]
Nevermind, I noticed that hex still has the right format. Will send a PR to update the example in the README if you don't do it very soon. 😄

**Comment by Licenser** [comment]
Reason for that is simply that the rebar3 hex plugin tags things that way

**Comment by aronisstav** [comment]
Thanks for the reply! Do you happen to know more about the reason it does that instead of using the tag that it puts on hex?

**Comment by Licenser** [comment]
I honestly do not, but I'm sure #rebar in IRC has the answer :)
